### ISSUE TITLE
nix-shell is broken on newest stable NixOS with freshly cloned repo

### ISSUE THREAD

**Issue by jaredpmclaughlin** [Haskell-Things/ImplicitCAD#402]
I am a first time NixOS user (day 2) attempting to build ImplicitCAD from the repo. I installed git, cloned ImplicitCAD and attempted to use the nix-shell. Here is the error I got:

![image](https://user-images.githubusercontent.com/56572863/154083102-9793d55a-16cd-48cb-aa5b-2f536931d66d.png)

**Comment by thiskappaisgrey** [comment]
Usually with nix, Haskell packages gets broken from time to time, due to infrastructure issues. Anyways, you can try to play around with https://github.com/nmattia/niv and switch your nixpkgs version to where a package is NOT broken. (if you look in the docs for niv, you'll see that you need to change `pkgs ? import <nixpkgs> {},` to `pkgs ? (import nix/sources.nix).nixpkgs {}` in `default.nix` and `shell.nix` ). Then you can do `niv init -b=release-21.05` in the root repo, and see if the haskell packages required for building implicitcad is broken there(I haven't built implicitcad in a while and struggled with the haskell nix infrastructure when I was starting out too.. still do actually). Hope that helps. If not you can try using a `default.nix` and `shell.nix` from https://input-output-hk.github.io/haskell.nix/ but that's a bit more complicated.

**Comment by sorki** [comment]
So the underlying issue was fixed and I plan to revisit this and pin nixpkgs to a working revision of unstable so it doesn't break.

haskell.nix would work for us as well and we might want to switch if we decide to e.g. do cross builds for other platforms.
